### PR TITLE
Fix experimental globals for SASS 3.3 and future versions

### PR DESCRIPTION
**Pull request by OlenDavis**
This will break the compass-animation plugin for SASS 3.2, but would be broken in versions of SASS after 3.3.

### CODE REVIEW

**Comment by mirisuzanne** [comment]
Why keep this plugin alive for 3.3, when it has completely moved into Compass?

**Comment by OlenDavis** [comment]
To cling desperately to relevance, duh! :D

**Comment by mirisuzanne** [comment]
Would you like to take over as maintainer of this project? :D

**Comment by OlenDavis** [comment]
About as much as I want to be a pig farmer in Saudi Arabia.

(But in all seriousness, thank you for this project, even if only "back in the day")

**Comment by mirisuzanne** [comment]
No problem!

**Pull request closed without merging**
