### PR TITLE
Update compass-animation to use the integrated Compass mixins

### PR DESCRIPTION
**Pull request by Anahkiasen**
I updated this now that all the functions it used have been ported to the core Compass mixins. Since it then had no use, I switched the basic import so that instead of importing the (now gone) mixins, it imports the keyframes.
I also added back a classes.scss as discussed in another issue, to restore external use of the animations.

### CODE REVIEW

**Comment by mirisuzanne** [comment]
I'm not ready to remove the animation mixins from this plugin until they reach a stable release of Compass. In the meantime, I'd love to include the flippers and classes (as long as they remain an optional import).

When these mixins do hit compass/stable, I'm not sure this is the right plugin for it anyway. Taking an optional feature and making it the central purpose of a plugin seems like a big leap: time to make a new plugin instead. Any interest in starting that as a plugin of your own?

**Comment by mirisuzanne** [comment]
I cherry-picked classes from you. The rest we can discuss.

**Comment by Anahkiasen** [comment]
Well to me it's perfect as is. I mostly did a pull request as a way to poke you for opinion and get you a little ahead in the changes you had to do. :)

**Comment by mirisuzanne** [comment]
Awesome. You should make your own gem out of that, and I'll send people your way when I kill mine. :)

(I agree, it's perfect. It's just a different plugin. If you release it, I'll use it. I just won't pull it.)

**Comment by mirisuzanne** [comment]
Wait, I may be wrong. I won't kill it, I'll just turn it over to you. That way it can still be the same plugin if you think it should be.

**Comment by Anahkiasen** [comment]
Well in my mind once the official animation goes stable, I thought compass-animation should focus on being a 1:1 scss conversion of Animate.css – at least that what seemed the most logical to me considering the code already present.

**Pull request closed without merging**
